### ISSUE TITLE
LGTM-Alert Polynomial regular expression used on uncontrolled data

### ISSUE THREAD

**Issue by Uzlopak** [fastify/fast-uri#42]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

see:
https://lgtm.com/projects/g/fastify/fast-uri/snapshot/a91fe052eb5fc4f8831c7fee0131457289db14a9/files/index.js?sort=name&dir=ASC&mode=list#x852651248d66d755:1

**Comment by Uzlopak** [comment]
I dont have a laptop the next 4 days, so if you want to wait that long, i could try. But i am not quite sure why you call match on not test.

I assume that you can fix it by doing, as the s-flag means that dot also matches newline
`/\/\/(?:.)*:(?:\/|\?|#|$)/s`

Or why do you need the non matching groups anyway, 

Maybe the original writer of that regex can give more insights?

**Comment by mcollina** [comment]
Totally, take your time. cc @zekth

**Comment by zekth** [comment]
This is relative to an old IE fix. I think we can drop the whole statement IMO

**Comment by mcollina** [comment]
Let's do it.

**Comment by Fdawgs** [comment]
> This is relative to an old IE fix. I think we can drop the whole statement IMO

Got a link or some additional info on that @zekth? Just curious as to what it was fixing.

**Comment by zekth** [comment]
I think this is related to this behavior https://stackoverflow.com/questions/28857067/regex-not-working-for-ie-but-works-for-other-browsers
