### ISSUE TITLE
escape & unescape are deprecated

### ISSUE THREAD

**Issue by budarin** [fastify/fast-uri#57]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

IDE shows me warning: these functions are deprecated

**Comment by climba03003** [comment]
I have no idea what you means.
And I don't see a deprecated notice in https://nodejs.org/dist/latest-v18.x/docs/api/deprecations.html

**Comment by budarin** [comment]
![image](https://user-images.githubusercontent.com/8055157/219887600-9022bdaa-d83f-4e12-bcd8-38712ce28c2a.png)

**Comment by Uzlopak** [comment]
Yeah maybe in lib.es5.d.ts it is marked as deprecated as it not part of the web browser standard. But it is not deprecated for nodejs.

**Comment by budarin** [comment]
Ok
