### ISSUE TITLE
Change require "url" to "node:url" did make it incompatible with usage inside browser / web

### ISSUE THREAD

**Issue by alexander-schranz** [fastify/fast-uri#82]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Plugin version

2.3.0

### Node.js version

v14.21.3

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.7.4

### Description

The changes in https://github.com/fastify/fast-uri/commit/6c97e357f7e0bc15a3dbbcf1c54c3b21c995d47a

seems to break packages which using it as example via webpack in the browser. I'm not 100% sure if this package was created to work inside browser but thought I would report it if it should.

Currently because of `node:url` the ajv is failing now which is package used for json schema validation in some cases as we in @sulu using it in browser: https://github.com/ajv-validator/ajv/issues/2446

### Link to code that reproduces the bug

https://github.com/ajv-validator/ajv/issues/2446

### Expected Behavior

Should work inside the browser / web apps compiles with webpack 4 / 5.

### Workaround

For all coming from https://github.com/ajv-validator/ajv/issues/2446 you can downgrade ajv to a version not using `fast-uri`:

```
npm install "ajv@8.14.*" --save
```

or downgrade fast-uro to:

```
npm install "fast-uri@2.2.*" --save
```

**Comment by LucasLopesr** [comment]
same problem here

**Comment by alexander-schranz** [comment]
@Eomm what ist your recommended solution. Should we revert #69.

And do you have any hint how we can add a test to check if it works inside browser?

**Comment by gurgunday** [comment]
Please remove to URL import altogether and make it use the global variable

**Comment by gurgunday** [comment]
I think there is still some work needed to do before we can make fast-uri run on the Web:

https://github.com/fastify/fast-uri/issues/21
