### ISSUE TITLE
bring back the support for Node.js v16

### ISSUE THREAD

**Issue by mcollina** [fastify/fast-uri#94]
Given our goal for fast-uri to be the default of ajv, I think we should bring back support for Node.js v16. This would mean:

* [x] switch to use tape instead of tap
* [x] use a custom action

**Comment by mcollina** [comment]
@gurgunday @jsumners wdyt?

**Comment by gurgunday** [comment]
Do we want a custom workflow to test it in the browser? I don’t understand why tape is needed

**Comment by mcollina** [comment]
latest tap does not support node v16 and v18.

**Comment by Uzlopak** [comment]
I think tape is acceptable in this case, because we could then also implement #21 easily, as it would be a copy paste solution from readable-stream repo.

**Comment by jsumners** [comment]
Won't AJV need to drop Node 16 in a few short (😭) months anyway?

**Comment by jasoniangreen** [comment]
I just released AJV 8.17.1 with fast-uri. I hadn't seen this, but you're right, we'd be looking at dropping it soon. Hopefully this doesn't cause too many problems. I mean, 16 is about 6 months over the maintenance window.

**Comment by gurgunday** [comment]
We now use `tape` and the CI successfully tests `fast-uri` on node 16

For browser support, it should be working already, and the custom CI to run automated browser tests can be tracked at https://github.com/fastify/fast-uri/issues/21
