### ISSUE TITLE
Inconsistent License Information

### ISSUE THREAD

**Issue by vagas87** [fastify/fast-uri#99]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

License file suggests some kind of 3-clause-BSD file (because it is not 100% the original license text), but package.json is set to MIT. Please clarify the license information on this library.

**Comment by zekth** [comment]
@mcollina do you know how we would handle this? Original license is https://github.com/garycourt/uri-js/blob/a1acf730b4bba3f1097c9f52e7d9d3aba8cdcaae/package.json#L56

Should we update the license to specify all the commits from `uri-js` are `BSD-2-Clause` and now `MIT` ?

**Comment by mcollina** [comment]
No. The license was _never_ MIT. What matters is the actual license text, not the package.json.

**Comment by mcollina** [comment]
Good spot @vagas87!

**Comment by vagas87** [comment]
Actually, kudos to my PO, who spotted this while checking SBOMs. He did not have his private GitHub credentials at hand when discovering this at work, so he asked me to open this issue for him 😅
